# Echecs d'authentification HTTP basique sur fail2ban-ui
# Status 401 = auth échouée

[Definition]
failregex = .*"ClientHost":"<HOST>".*"RequestAddr":"fail2ban\.azteas\.com".*"DownstreamStatus":401.*
ignoreregex =
