# Echecs d'authentification HTTP basique sur le dashboard Traefik
# Status 401 = auth échouée

[Definition]
failregex = .*"ClientHost":"<HOST>".*"RequestAddr":"traefik\.azteas\.com".*"DownstreamStatus":401.*
ignoreregex =
