services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://umami:${UMAMI_DB_PASSWORD}@postgresql:5432/umami
      - APP_SECRET=${UMAMI_APP_SECRET}
    labels:
      - traefik.enable=true
      - traefik.docker.network=azteas-net
      - traefik.http.routers.umami.entrypoints=websecure
      - traefik.http.routers.umami.rule=Host(`analytics.azteas.com`)
      - traefik.http.routers.umami.tls=true
      - traefik.http.routers.umami.tls.certresolver=letsencrypt
      - traefik.http.routers.umami.middlewares=rate-limit@file
      - traefik.http.services.umami-svc.loadbalancer.server.port=3000
    networks:
      - azteas-net

networks:
  azteas-net:
    external: true
    name: azteas-net
