http:
  routers:
    azteas-admin:
      rule: "Host(`apanel.azteas.com`)"
      entryPoints:
      - websecure
      tls:
        certResolver: letsencrypt
      service: azteas-admin-svc

  services:
    azteas-admin-svc:
      loadBalancer:
        servers:
        - url: "http://azteas-admin:3000"
